name: Upgrade requirements

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.branch }}

      # Update Dockerfile line
      - name: Update Dockerfile
        run: |
          lib_name=${{ github.event.client_payload.lib_name }}
          lib_vers=${{ github.event.client_payload.lib_vers }}
          sed -E -i "s/ver_${lib_name}=.+/ver_${lib_name}=${lib_vers}/1" Dockerfile-3-9
          sed -E -i "s/ver_${lib_name}=.+/ver_${lib_name}=${lib_vers}/1" Dockerfile-3-10
          sed -E -i "s/ver_${lib_name}=.+/ver_${lib_name}=${lib_vers}/1" Dockerfile-3-11

      # Commit modifications to Dockerfile
      - name: Commit changes
        run: |
          lib_name=${{ github.event.client_payload.lib_name }}
          lib_vers=${{ github.event.client_payload.lib_vers }}
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -a -m "bump: bumpver ${lib_name} to ${lib_vers}"
          git push
